title: Secyruty & Privacy and AI Conference Deadlines # (Maintained by @llCurious)
# email: abhshkdz@vt.edu
description: Countdowns to top NLP/ML/AI/SC/SJ conference deadlines
author: Haoqi Wu 

domain: "llcurious.github.io"
baseurl: ""

twitter_username: none
twitter_hashtag: none
github_username: llCurious
github_repo: llCurious.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
